version: '3'

services:
    mariadb:
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
            args:
              - WP_DB_NAME
              - ADMIN_USER
              - ADMIN_PASS
        container_name: mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
          - /home/fporto/data/mariadb/:/var/lib/mysql/
        networks:
          - web-network



    wordpress:
        depends_on:
          - mariadb
          - redis
        build:
            context: requirements/wordpress/
            dockerfile: Dockerfile
        container_name: wordpress
        restart: unless-stopped
        env_file: .env
        volumes:
          - /home/fporto/data/website-root/:/var/www/html/
        networks:
          - web-network



    nginx:
        depends_on:
          - wordpress
          - static-website
          - adminer
          - portainer
        build:
            context: requirements/nginx/
            dockerfile: Dockerfile
            args:
              - DOMAIN_NAME
              - ADMIN_USER
        container_name: nginx
        restart: unless-stopped
        env_file: .env
        volumes:
          - /home/fporto/data/nginx/:/var/log/nginx/
          - /home/fporto/data/ssl/:/ssl/
          - /home/fporto/data/website-root/:/var/www/html/
        ports:
          - "443:443"
        networks:
          - web-network



    redis:
        build:
            context: bonus/redis
            dockerfile: Dockerfile
        container_name: redis
        restart: unless-stopped
        volumes:
          - /home/fporto/data/redis/log/:/var/log/redis/
          - /home/fporto/data/redis/db/:/var/lib/redis/
        networks:
          - web-network



    vsftpd:
        depends_on:
          - wordpress
        build:
            context: bonus/vsftpd
            dockerfile: Dockerfile
            args:
              - ADMIN_USER
              - ADMIN_PASS
        container_name: vsftpd
        restart: unless-stopped
        env_file: .env
        volumes:
          - /home/fporto/data/ssl/:/ssl/:ro
          - /home/fporto/data/vsftpd/:/var/log/vsftpd/
          - /home/fporto/data/website-root/:/ftp/wordpress/
        ports:
          - "21:21"
          - "40000-40005:40000-40005"



    static-website:
        build:
            context: bonus/static-website
            dockerfile: Dockerfile
        container_name: static-website
        restart: unless-stopped
        networks:
          - web-network



    adminer:
        depends_on:
          - mariadb
        build:
            context: bonus/adminer
            dockerfile: Dockerfile
        container_name: adminer
        restart: unless-stopped
        networks:
          - web-network



    portainer:
        build:
            context: bonus/portainer
            dockerfile: Dockerfile
        container_name: portainer
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/fporto/data/portainer/:/data/
        networks:
          - web-network



networks:
    web-network:
        driver: bridge
