version: '3'

services:
    mariadb:
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
            args:
              - WP_DB_NAME
              - ADMIN_USER
              - ADMIN_PASS
        container_name: mariadb
        image: mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
          - mariadb:/var/lib/mysql/
        networks:
          - inception



    wordpress:
        depends_on:
          - mariadb
          - redis
        build:
            context: requirements/wordpress/
            dockerfile: Dockerfile
        container_name: wordpress
        image: wordpress
        restart: unless-stopped
        env_file: .env
        volumes:
          - website-root:/var/www/html/
        networks:
          - inception



    nginx:
        depends_on:
          - wordpress
          - static-website
          - adminer
          - uptime-kuma
          # - portainer
        build:
            context: requirements/nginx/
            dockerfile: Dockerfile
            args:
              - DOMAIN_NAME
              - ADMIN_USER
        container_name: nginx
        image: nginx
        restart: unless-stopped
        env_file: .env
        volumes:
          - nginx:/var/log/nginx/
          - ssl:/ssl/
          - website-root:/var/www/html/
        ports:
          - "443:443"
        networks:
          - inception



    redis:
        build:
            context: bonus/redis
            dockerfile: Dockerfile
        container_name: redis
        image: redis
        restart: unless-stopped
        volumes:
          - redis_log:/var/log/redis/
          - redis_db:/var/lib/redis/
        networks:
          - inception



    vsftpd:
        depends_on:
          - wordpress
        build:
            context: bonus/vsftpd
            dockerfile: Dockerfile
            args:
              - ADMIN_USER
              - ADMIN_PASS
        container_name: vsftpd
        image: vsftpd
        restart: unless-stopped
        env_file: .env
        volumes:
          - ssl:/ssl:ro
          - vsftpd:/var/log/vsftpd/
          - website-root:/ftp/wordpress/
        ports:
          - "21:21"
          - "40000-40005:40000-40005"



    static-website:
        build:
            context: bonus/static-website
            dockerfile: Dockerfile
        container_name: static-website
        image: static-website
        restart: unless-stopped
        networks:
          - inception



    adminer:
        depends_on:
          - mariadb
        build:
            context: bonus/adminer
            dockerfile: Dockerfile
        container_name: adminer
        image: adminer
        restart: unless-stopped
        networks:
          - inception



    uptime-kuma:
        build:
            context: bonus/uptime-kuma
            dockerfile: Dockerfile
        container_name: uptime-kuma
        image: uptime-kuma
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - uptime-kuma:/uptime-kuma/data/
        networks:
          - inception



    # portainer:
    #     build:
    #         context: bonus/portainer
    #         dockerfile: Dockerfile
    #     container_name: portainer
    #     image: portainer
    #     restart: unless-stopped
    #     volumes:
    #       - /var/run/docker.sock:/var/run/docker.sock
    #       - portainer:/data/
    #     networks:
    #       - inception



volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            o: bind
            device: mariadb
    website-root:
        name: website-root
        driver: local
        driver_opts:
            type: none
            o: bind
            device: website-root
    nginx:
        name: nginx
        driver: local
        driver_opts:
            type: none
            o: bind
            device: nginx
    ssl:
        name: ssl
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ssl
    redis_log:
        name: redis_log
        driver: local
        driver_opts:
            type: none
            o: bind
            device: redis_log
    redis_db:
        name: redis_db
        driver: local
        driver_opts:
            type: none
            o: bind
            device: redis_db
    vsftpd:
        name: vsftpd
        driver: local
        driver_opts:
            type: none
            o: bind
            device: vsftpd
    uptime-kuma:
        name: uptime-kuma
        driver: local
        driver_opts:
            type: none
            o: bind
            device: uptime-kuma



networks:
    inception:
        driver: bridge
