CREATE DATABASE IF NOT EXISTS {$MYSQL_DB_NAME};
CREATE USER IF NOT EXISTS '{$MYSQL_USER}'@'%' IDENTIFIED BY '{$MYSQL_USER_PASS}';
GRANT ALL PRIVILEGES ON {$MYSQL_DB_NAME}.* TO '{$MYSQL_USER}'@'%';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{$MYSQL_ROOT_PASS}');
FLUSH PRIVILEGES;
